InsightSoftwareConsortium/ITKModuleTemplate

CTestConfig.cmake
The enables uploads of build/test results to ITK's CDash dashboard at
https://open.cdash.org with commands like
ctest -D Experimental
=> ENH: Add ITK CTestConfig.cmake

.circleci/config.yml, {{cookiecutter.project_name}}/.circleci/config.yml
CircleCI systems have a large number of processors detected by ninja, but the
containers are provided with access to limited memory. This can cause builds
to fail when they run out of memory. Limit the number of parallel build
processes.
=> BUG: Limit CircleCI build parallelism

.circleci/config.yml, {{cookiecutter.project_name}}/.circleci/config.yml
This enables uploading of the revision to CTest in the update field and more
control over the CTest build configuration.
=> ENH: Use CTest script for CircleCI build

{{cookiecutter.project_name}}/src/CMakeLists.txt
This newer macro is the simpler and preferred way to add libraries for
modules.
=> ENH: Use itk_module_add_library macro

{{cookiecutter.project_name}}/test/CMakeLists.txt
This variable includes module dependency libraries from TEST_DEPENDS
=> BUG: Link to correct libraries variable in the tests

README.rst
To avoid confusion with ITKv5.
Addresses #26
=> DOC: Use "ITK" instead of "ITKv4" to refer to the module system

{{cookiecutter.project_name}}/CMakeLists.txt
As agreed in:
https://discourse.itk.org/t/cmake-update/870/
Set the `cmake_minimum_required` to version **3.10.2**.
=> COMP: Set the minimum required CMake version to 3.10.2.

.travis.yml, {{cookiecutter.project_name}}/.travis.yml
filebin.ca is no longer reliable.
=> BUG: Use transfer.sh for macOS package upload

README.rst
Update the reference concerning the `Contributing with a Remote Module`
section: change the reference to the **wiki** for a reference to the **Software
Guide**. This part of the toolkit documentation was migrated to the SWG in
order to reduce the number of sites to look at when searching
documentation.
=> DOC: Change reference to wiki for SWG reference.

{{cookiecutter.project_name}}/test/itkNormalDistributionImageSourceTest.cxx
Remove unnecessary white space before comma in function argument list.
=> STYLE: Remove unnecessary white space before comma.

{{cookiecutter.project_name}}/include/itkNormalDistributionImageSource.h, {{cookiecutter.project_name}}/include/itkNormalDistributionImageSource.hxx
git bisect reveals that the test started failing with
InsightSoftwareConsortium/ITK@4627a89f15e8cf6fc5f0fe6c3ff7e9221ce32db3
which is related to the number of work units used in the pool
multi-threader.
Simply consistent output generation by removing threading from the
example filter.
=> BUG: Fix NormalDistributionImageSource test

{{cookiecutter.project_name}}/include/itkMinimalStandardRandomVariateGenerator.h, {{cookiecutter.project_name}}/include/itkNormalDistributionImageSource.hxx, {{cookiecutter.project_name}}/include/itk{{cookiecutter.filter_name}}.h
Prefer C++11 type alias over `typedef` for the reasons stated here:
http://review.source.kitware.com/#/c/23103/
=> STYLE: Prefer C++11 type alias over typedef.

{{cookiecutter.project_name}}/include/itkMinimalStandardRandomVariateGenerator.h
Use the `ITK_DISALLOW_COPY_AND_ASSIGN` macro to enhance consistency across
the the toolkit when disallowing the copy constructor and the assign
operator.
Move the `ITK_DISALLOW_COPY_AND_ASSIGN` calls to public section following
the discussion in
https://discourse.itk.org/t/itk-disallow-copy-and-assign/648
=> COMP: Use and move ITK_DISALLOW_COPY_AND_ASSIGN calls to public section.

{{cookiecutter.project_name}}/include/itkMinimalStandardRandomVariateGenerator.h, {{cookiecutter.project_name}}/include/itk{{cookiecutter.filter_name}}.h
This check replaces default bodies of special member functions with
= default;. The explicitly defaulted function declarations enable more
opportunities in optimization, because the compiler might treat
explicitly defaulted functions as trivial.
Additionally, the C++11 use of = default more clearly expreses the
intent for the special member functions.
=> STYLE: Pefer = default to explicitly trivial implementations.

azure-pipelines.yml, {{cookiecutter.project_name}}/test/azure-pipelines.yml
By separating the tags, we can use different versions of ITK for C++ and Python builds. In this way, we can use, for example, a Git commit hash for the C++ version, and an unrelated tag name for the Python version.
@jhlegarreta since the testing macro *ITK_* prefix came in after v5.0.0 was tagged, with this change, we can set  *ITKGitTag* to a later version of ITK Git *master* and keep *ITKPythonGitTag* to *v5.0.0.post1*.
=> ENH: Use separate ITK Git tags for C++ and Python CI

azure-pipelines.yml, {{cookiecutter.project_name}}/test/azure-pipelines.yml
These are optional and they interfere with the ITK/Utilities/Maintenance/UpdateRequiredITKVersionInRemoteModules.sh
script.
=> BUG: Remove quotes from ITK version in Azure configuration

{{cookiecutter.project_name}}/test/azure-pipelines.yml
So we can choose an arbitrary ITK Git hash to build a given remote
module against.
=> ENH: Support arbitrary ITK version for C++ CI testing

{{cookiecutter.project_name}}/test/itk{{cookiecutter.filter_name}}Test.cxx
Use the `itkNameOfTestExecutableMacro` to get the test name and prevent
the the test from crashing when `argv[0]` is null, as recommended in:
https://github.com/InsightSoftwareConsortium/ITK/pull/564
=> ENH: Use the `itkNameOfTestExecutableMacro` to get the test name

{{cookiecutter.project_name}}/.github/workflows/build-test-package.yml
In CI, this is unnecessary now because every Python package version is
generated in a clean virtual machine instance. On some packages that use
CMake FetchContent, the cleanup step can fail with:
Adding 'itk_elastix-0.6.0.dist-info/RECORD'
removing _skbuild\win-amd64-3.5\setuptools\bdist.win-amd64\wheel
C:\P\IPP\venv-35-x64\lib\site-packages\wheel\pep425tags.py:82: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
warn=(impl == 'cp')):
C:\P\IPP\venv-35-x64\lib\site-packages\wheel\pep425tags.py:87: RuntimeWarning: Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
sys.version_info < (3, 8))) \
running clean
removing '_skbuild\win-amd64-3.5\cmake-install'
removing '_skbuild\win-amd64-3.5\cmake-build'
error: [WinError 5] Access is …
=> BUG: Add --no-clean flag to Windows Python package generation step

.github/workflows/build-test-package.yml, {{cookiecutter.project_name}}/.github/workflows/build-test-package.yml, {{cookiecutter.project_name}}/setup.py
Adds package improvements. All remote modules should update their CI to
build against itk v5.1.0.post2 and their setup.py dependency to
itk>=5.1.0.post2
=> BUG: Build Python packages against v5.1.0.post2

{{cookiecutter.project_name}}/README.rst
An extraneous end parenthesis has been removed, which was resulting
in a 404 error when trying to access the LICENSE file via the badge.
=> BUG: Fix 404 Error in License Badge Link

.github/workflows/build-test-package.yml, {{cookiecutter.project_name}}/.github/workflows/build-test-package.yml, {{cookiecutter.project_name}}/setup.py
Python 3.6 is now minimum. Version 3.5 has reached end of life.
=> ENH: update minimum Python version from 3.5 to 3.6

.github/workflows/build-test-package.yml, {{cookiecutter.project_name}}/.github/workflows/build-test-package.yml
This PR adds ITK runtime directory in PATH for Windows. The commit 1ad4cfbe033c2016bbdceb511f4694746cac70d4 adresses the problem discussed [here](https://discourse.itk.org/t/io-dlls-not-found/3464). It is not clear to me if this is a good solution, if this should be put in the cmd shell part of the yml file (I tried but it failed, see SimonRit/RTK@6373cb5a8ffa3f7d0a66912306a10e3ee07fa4f2), or if this should be addressed in RTK CMakeLists.txt... Let me know what you think.
cc @LucasGandel
=> Add ITK runtime directory in PATH for Windows

.github/workflows/build-test-package.yml, {{cookiecutter.project_name}}/.github/workflows/build-test-package.yml
Work around a regression in CMake 3.19.1 causing configuration errors:
CMake Error: install(EXPORT "ITKTargets" ...) includes target "gdcmjpeg8"
xref: https://gitlab.kitware.com/cmake/cmake/-/issues/21529
Install CMake 3.18.3.
=> COMP: Use CMake 3.18.3

.github/workflows/clang-format-linter.yml, {{cookiecutter.project_name}}/.github/workflows/clang-format-linter.yml
Recent checks fail to checkout the required commit.
=> BUG: Do not use shallow version of checkout for clang format linting

README.md, {{cookiecutter.project_name}}/README.rst
Include target for the GitHub Actions badge associated with the `README` of both the `ITKModuleTemplate` project and the cookiecutter template.
For future reference, URLs for both the badge image and the associated target where obtained like this:
`
=> ENH: Improve Github Actions badge to include target

README.md
This commit fixes regression introduced in b254407 (ENH: Improve Github
Actions badge to include target) removing extraneous parenthesis.
=> BUG: Fix rendering of badge in top-level README [ci skip]

.github/workflows/build-test-package.yml, README.md, {{cookiecutter.project_name}}/.clang-format, {{cookiecutter.project_name}}/.editorconfig, {{cookiecutter.project_name}}/.github/workflows/build-test-package.yml, {{cookiecutter.project_name}}/include/itkMinimalStandardRandomVariateGenerator.h, {{cookiecutter.project_name}}/include/itk{{cookiecutter.filter_name}}.h, {{cookiecutter.project_name}}/include/itk{{cookiecutter.filter_name}}.hxx, {{cookiecutter.project_name}}/src/itkMinimalStandardRandomVariateGenerator.cxx, {{cookiecutter.project_name}}/test/itkMinimalStandardRandomVariateGeneratorTest.cxx, {{cookiecutter.project_name}}/test/itk{{cookiecutter.filter_name}}Test.cxx
https is more tamper-resistant and more private so we use it instead
of http when it is available.
Following
https://github.com/InsightSoftwareConsortium/ITK/pull/3428/commits/9cd0f2053f0cf181ec4412bf896301faf0cc2092
Bump the ITK commit hash so that the above changes are accepted by the
ITK style checker.
=> ENH: Use https instead of http when https works

.github/workflows/build-test-package.yml, {{cookiecutter.project_name}}/.github/workflows/build-test-package.yml
Switch Github Actions macOS environment version to `macos-11`.
`macOS-10.15` is being deprecated and supported will end by 8/30/2022:
https://github.com/actions/virtual-environments/issues/5583
Related to recent warnings in the Azure Pipelines macOS environment
being used in the main ITK repository:
https://github.com/InsightSoftwareConsortium/ITK/pull/3532/commits/e5595dee1917e94ecc3c7f94873841b0f522d3c0
=> ENH: Switch Github Actions macOS environment

.github/workflows/build-test-package.yml, {{cookiecutter.project_name}}/.github/workflows/build-test-package.yml, {{cookiecutter.project_name}}/setup.py
Updates:
- Bumps ITK C++ and Python tags to v5.3rc04.post3
- Updates docker "_2_28" image
- Updates XCode version used to build ITK MacOS archives
=> ENH: Apply fixes for updated ITK v5.3rc04.post3 build config

.github/workflows/build-test-package.yml, {{cookiecutter.project_name}}/.github/workflows/build-test-package.yml
As Linux comes with some version of CMake,
this problem sneaked in without detection.
If CMake version is important, this difference
between version on different OSes can be confusing.
=> ENH: Specify the same CMake version for Linux Python package builds

.github/workflows/build-test-package.yml, {{cookiecutter.project_name}}/.github/workflows/build-test-package.yml
Re-write versions as strings rather than numbers because 3.1 != 3.10, etc.  Nothing is broken at present but in the future as, e.g., the Python version for some things goes from 3.8 to 3.9 to 3.10, this could end up being an unexpected problem.
=> ENH: Versions as strings, not numbers, so that 3.1 != 3.10, etc.

.github/workflows/build-test-package.yml, .github/workflows/clang-format-linter.yml, {{cookiecutter.project_name}}/.github/workflows/clang-format-linter.yml
Fix `Node.js` warnings linked to GitHub actions: upgrade to
`actions/checkout@v3` and `actions/setup-python@v3`.
Fixes:
```
cov / build (3.9, ubuntu-latest, pip)
Node.js 12 actions are deprecated.
For more information see:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16:
actions/checkout@v2, actions/setup-python@v2
```
raised for example in:
https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/actions/runs/3594726041
Fixes issue #141  (replaces #144)
=> ENH: Upgrade GitHub actions to `checkout@v3` and `setup-python@v3`

.github/workflows/build-test-package.yml
Fix workflow actions warnings linked to `Node.js: bump miscellaneous GitHub actions versions in workflow.
Fixes:
```
build-test-cxx (windows-2022)
Node.js 12 actions are deprecated. For more information see:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16: lukka/get-cmake@v3.22.2
```
and
```
build-test-cxx (windows-2022)
The `set-output` command is deprecated and will be disabled soon.
Please upgrade to using Environment Files. For more information see:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
raised for example in:
https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/actions/runs/3669019278 …
=> ENH: Fix workflow actions warnings linked to `Node.js`

.github/workflows/build-test-package.yml
Drop Python 3.7 from CI build matrices: Python 3.7 reached its EOL on 2023-06-27.
=> ENH: Drop Python 3.7 from CI build matrices

.github/workflows/build-test-package.yml
Specify Python versions for macOS CI builds.
=> ENH: Specify Python versions for macOS CI builds

.github/workflows/build-test-package.yml, {{cookiecutter.project_name}}/.github/workflows/build-test-package.yml, {{cookiecutter.project_name}}/pyproject.toml
Update CI to build against v5.4.0
Also, improve how the `itk` python package version dependency is
specified. Uses `== 5.4.*` to indicated compatibility with 5.4.0, 5.4.1,
5.4.2, etc., but not 5.5.0, etc. There is generally binary
incompatibilty between minor versions. While it is possible that there
could be binary incompatibility between patch releases, it is more
likely that they will be compatible. This flexibilty helps ensure
that remote module packages are not assumed invalid when a new patch
version of `itk` is released. Addresses #142
=> ENH: Updates for ITK 5.4.0

.github/workflows/build-test-package.yml, {{cookiecutter.project_name}}/.github/workflows/build-test-package.yml
When a branch is pushed to the same repository, i.e. not a fork, and a
pull request is made, duplicate builds will be generated for both the
pull request and push. Instead, only generate builds for pull requests
against main and pushes to main.
=> BUG: Prevent duplicate builds on pull request, push

{{cookiecutter.project_name}}/include/itkMinimalStandardRandomVariateGenerator.h, {{cookiecutter.project_name}}/include/itk{{cookiecutter.filter_name}}.h
See related ITK PRs:
https://github.com/InsightSoftwareConsortium/ITK/pull/4373
https://github.com/InsightSoftwareConsortium/ITK/pull/4378
We should probably wait until ITK 5.4 final is tagged, before merging this.
=> ENH: Use itkOverrideGetNameOfClassMacro as per ITK PR 4373

cookiecutter.json, {{cookiecutter.project_name}}/CMakeLists.txt, {{cookiecutter.project_name}}/examples/CMakeLists.txt, {{cookiecutter.project_name}}/examples/{{ cookiecutter.example_name }}.cxx, {{cookiecutter.project_name}}/examples/{{ cookiecutter.example_name }}.py
Add a hint to foster writing examples for the contributed classes.
Resolves #34.
=> ENH: Add examples to the template.

.github/workflows/build-test-package.yml
- BUG: Use a different name for each macOS wheel name
- STYLE: Make the wheel names consistent
=> BUG: Use a different name for each macOS wheel name

.github/workflows/build-test-package.yml, .github/workflows/clang-format-linter.yml, {{cookiecutter.project_name}}/.github/workflows/clang-format-linter.yml
Fix `Node.js` warnings linked to GitHub actions: bump `actions/checkout@v4`.
Take advantage of the commit to bump `upload-artifact@v4` and `actions/setup-python@v5`.
Fixes:
```
Node.js 16 actions are deprecated.
Please update the following actions to use Node.js 20:
actions/checkout@v3.
For more information see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
raised for example in:
https://github.com/InsightSoftwareConsortium/ITKTrimmedPointSetRegistration/actions/runs/9753007352
=> ENH: Fix `Node.js` warnings linked to GitHub actions

{{cookiecutter.project_name}}/.github/workflows/build-test-package.yml
As a follow-up, we need to build on tags to deploy to PyPI.
=> BUG: Build python packages on tags for deployment
